"""Workspace export for SweTask to directory format.

Structure finale dans le container Docker:
- /workspace/repo/     - Le code source du repository
- /workspace/forge/    - Fichiers générés par SWE-Forge (CACHÉ pendant l'exécution agent)
  ├── tests/          - Tests générés
  ├── patch.diff      - Le patch à appliquer
  ├── workspace.yaml  - Configuration de la tâche
  └── README.md       - Instructions pour l'agent

IMPORTANT: Le dossier /forge/ doit être caché (exclu du contexte) pendant que l'agent
travaille pour éviter qu'il ne "triche" en regardant directement les solutions.
"""

import re
from logging import getLogger
from pathlib import Path
from typing import Any

import yaml

from swe_forge.exceptions import DiscoveryError
from swe_forge.export.docker_verify import generate_evaluate_script, generate_run_script
from swe_forge.swe.models import SweTask

logger = getLogger(__name__)

# Chemins standards dans le container Docker
FORGE_DIR = "/workspace/forge"
REPO_DIR = "/workspace/repo"
TESTS_DIR = f"{FORGE_DIR}/tests"

def _extract_test_file_names(test_patch: str) -> list[str]:
    """Extract test file names from test_patch diff.

    Returns full paths like 'tests/test_foo.py' (not just filename).
    """
    header_pattern = r"^#\s*(tests/[a-zA-Z0-9_/]+\.py)\s*$"
    header_matches = re.findall(header_pattern, test_patch, re.MULTILINE)

    diff_pattern = r"\+\+\+ b/(tests/[a-zA-Z0-9_/]+\.py)"
    diff_matches = re.findall(diff_pattern, test_patch)

    all_files = header_matches + diff_matches
    return list(dict.fromkeys(all_files))


def _transform_test_commands(commands: list[str]) -> list[str]:
    """Transform test commands from sandbox paths to final Docker paths.

    Sandbox uses /repo, final Docker uses /workspace/repo for code
    and /workspace/forge/tests for generated tests.
    """
    transformed = []
    for cmd in commands:
        new_cmd = cmd
        new_cmd = new_cmd.replace("/repo", REPO_DIR)
        test_pattern = re.compile(r"(?:/repo/|/workspace/repo/)?tests/(test_\w+\.py)")
        if test_pattern.search(new_cmd):
            new_cmd = test_pattern.sub(lambda m: f"{TESTS_DIR}/{m.group(1)}", new_cmd)
        transformed.append(new_cmd)
    return transformed


def _generate_forge_readme() -> str:
    """Generate README.md for /forge/ directory."""
    return """# SWE-Forge Generated Files

⚠️ **IMPORTANT FOR AGENT EXECUTION** ⚠️

This `/forge/` directory contains SWE-Forge generated files and must be 
**HIDDEN from the agent** during task execution.

## How to Hide

When running an agent to solve this task, exclude this directory from the agent's context:

### For OpenHands / SWE-Agent:
```bash
# Add to .gitignore or use exclusion patterns
export FORGE_EXCLUDE="--exclude /workspace/forge"
```

### For Docker containers:
```bash
# Mount with restricted permissions
docker run --rm -v /workspace/forge:/forge:ro ...
```

### For file search tools:
```python
# Exclude /forge/ from search results
if "/forge/" in path or "/workspace/forge" in path:
    continue  # Skip this file
```

## Directory Structure

```
/workspace/forge/
├── tests/          # Generated behavioral tests
├── patch.diff      # The patch to apply (SOLUTION - DO NOT SHOW AGENT)
├── test_patch.diff # Original test patch from PR
├── workspace.yaml  # Task configuration
└── README.md       # This file
```

## Why Hide?

1. **patch.diff** contains the actual solution - showing it would be cheating
2. **workspace.yaml** may contain hints about the fix
3. Tests should be discovered by reasoning, not by reading them directly

## Purpose

These files are used by SWE-Forge to:
1. Verify the FAIL→PASS cycle
2. Build Docker images for evaluation
3. Generate training datasets

## After Agent Finishes

Once the agent completes, you can:
1. Apply the patch: `git apply /workspace/forge/patch.diff`
2. Run tests: `pytest /workspace/forge/tests/`
3. Compare agent's solution with the actual patch

---
Generated by SWE-Forge | https://github.com/swe-forge
"""


def export_task_to_workspace(
    task: SweTask,
    output_folder: Path | str,
    docker_username: str | None = None,
    prebuilt_image: bool = False,
    overwrite: bool = False,
) -> Path | None:
    import shutil

    output_folder = Path(output_folder)
    task_dir = output_folder / task.id

    if task_dir.exists():
        if overwrite:
            shutil.rmtree(task_dir)
        else:
            logger.warning(f"Task directory already exists, skipping: {task_dir}")
            return None

    task_dir.mkdir(parents=True, exist_ok=True)

    # Docker image
    docker_image = f"{docker_username}/swe-forge:{task.id}" if docker_username else None

    # Get install commands from config
    install_commands = task.install_config.get("install_commands", [])
    has_install_commands = bool(install_commands)

    # Get test commands from the task (generated by agent)
    fail_to_pass = list(task.fail_to_pass) if task.fail_to_pass else []
    pass_to_pass = list(task.pass_to_pass) if task.pass_to_pass else []

    test_file_paths = []
    if task.test_patch:
        test_file_paths = _extract_test_file_names(task.test_patch)

    if not fail_to_pass and test_file_paths:
        fail_to_pass = [
            f"pytest /workspace/forge/tests/{Path(tf).name} -v"
            for tf in test_file_paths
        ]
    # No transformation - agent commands should already have correct paths

    # Warn if no test commands but continue
    if not fail_to_pass and not task.test_patch:
        logger.warning(f"No test commands for task {task.id}")

    # Determine language - ensure it's properly detected
    language = task.language
    # Fix: if patch modifies yaml files but repo is Python, keep as python
    if language in ("yaml", "yml") and task.test_patch:
        # Check if test content is Python
        if "import pytest" in task.test_patch or "def test_" in task.test_patch:
            language = "python"
            logger.info(
                f"Corrected language from {task.language} to python for {task.id}"
            )

    # Build workspace data with new structure
    workspace_data: dict[str, Any] = {
        "task_id": task.id,
        "repo": {
            "url": f"https://github.com/{task.repo}.git",
            "base_commit": task.base_commit,
            "merge_commit": task.merge_commit,
            "path": REPO_DIR,  # Where repo will be cloned
        },
        "language": language,
        "difficulty_score": task.difficulty_score,
        "prompt": task.dataset_prompt if task.dataset_prompt else task.prompt,
        "environment": {
            "image": docker_image
            if docker_image
            else f"platformnetwork/swe-forge:{task.id}",
            "language_version": (
                task.install_config.get("language_version", "3.12")
                if language == "python"
                else "unknown"
            ),
            "repo_path": REPO_DIR,
            "forge_path": FORGE_DIR,
            "tests_path": TESTS_DIR,
        },
        "install": {
            "commands": install_commands,
            "working_dir": REPO_DIR,  # Install commands run in repo
        },
        "tests": {
            "fail_to_pass": fail_to_pass,
            "pass_to_pass": pass_to_pass,
            "working_dir": REPO_DIR,  # Tests run from repo, can access forge tests
        },
    }

    # Add docker section if image specified
    if docker_image:
        workspace_data["docker"] = {
            "image": docker_image,
            "build": not prebuilt_image,
            "prebuilt": prebuilt_image,
        }

    if task.meta:
        workspace_data["meta"] = task.meta

    # Write workspace.yaml
    workspace_path = task_dir / "workspace.yaml"
    with open(workspace_path, "w", encoding="utf-8") as f:
        yaml.dump(
            workspace_data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    # Write patch (ensure trailing newline for git apply)
    if task.patch:
        patch_path = task_dir / "patch.diff"
        patch_content = task.patch if task.patch.endswith("\n") else task.patch + "\n"
        with open(patch_path, "w", encoding="utf-8") as f:
            f.write(patch_content)

    # Write test patch
    if task.test_patch:
        test_patch_path = task_dir / "test_patch.diff"
        with open(test_patch_path, "w", encoding="utf-8") as f:
            f.write(task.test_patch)

    # Create tests directory and extract test files
    tests_dir = task_dir / "tests"
    tests_dir.mkdir(exist_ok=True)
    if task.test_patch:
        _extract_test_files(task.test_patch, tests_dir)

    # Write generated test files (from LLM TestGenerator)
    if task.generated_test_files:
        for tf in task.generated_test_files:
            rel_path = Path(tf["path"])
            target = tests_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            with open(target, "w", encoding="utf-8") as f:
                f.write(tf["content"])
            logger.info(f"Wrote generated test: {target}")

    # Write README.md explaining the forge directory should be hidden
    readme_path = task_dir / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(_generate_forge_readme())

    # Generate run_tests.sh script for easy Docker verification
    try:
        generate_run_script(task_dir)
    except Exception as e:
        logger.warning(f"Could not generate run script: {e}")

    # Generate evaluate.sh - binary score 0/1 evaluator
    try:
        repo_url = f"https://github.com/{task.repo}.git"
        generate_evaluate_script(
            task_dir,
            fail_to_pass=fail_to_pass,
            pass_to_pass=pass_to_pass,
            install_commands=install_commands,
            base_commit=task.base_commit,
            repo_url=repo_url,
        )
    except Exception as e:
        logger.warning(f"Could not generate evaluate script: {e}")

    return task_dir


def export_tasks_to_workspace(
    tasks: list[SweTask],
    output_folder: Path | str,
    docker_username: str | None = None,
    prebuilt_images: bool = False,
) -> list[Path]:
    """Export list of SweTask to workspace directories.

    Args:
        tasks: List of SweTask to export
        output_folder: Directory to export to
        docker_username: Docker Hub username for image names
        prebuilt_images: If True, indicates images are pre-built

    Returns:
        List of paths to task directories
    """
    import shutil
    from logging import getLogger

    logger = getLogger(__name__)
    output_folder = Path(output_folder)
    output_folder.mkdir(parents=True, exist_ok=True)

    results = []
    for task in tasks:
        task_dir = output_folder / task.id
        try:
            path = export_task_to_workspace(
                task, output_folder, docker_username, prebuilt_images, overwrite=True
            )
            if path is not None:
                results.append(path)
        except DiscoveryError as e:
            logger.warning(f"Skipping task {task.id}: {e}")
            if task_dir.exists():
                shutil.rmtree(task_dir)
        except Exception as e:
            logger.error(f"Error exporting task {task.id}: {e}")
            if task_dir.exists():
                shutil.rmtree(task_dir)

    return results


def _extract_test_files(test_patch: str, tests_dir: Path) -> None:
    """Extract test files from test_patch.

    Handles multiple formats:
    1. "# tests/path/to/file.py" header format (PRIMARY - from TestGenerator)
    2. "# Test file: path" format (legacy)
    3. Git diff format (diff --git ... +lines)
    """
    tests_dir.mkdir(parents=True, exist_ok=True)

    def safe_filename(name: str, max_len: int = 200) -> str:
        """Create safe filename, truncating if too long."""
        safe = re.sub(r'[<>:"/\\|?*]', "_", name)
        if len(safe) > max_len:
            safe = safe[:max_len]
        return safe

    # Format 1: "# tests/test_foo.py" header format (NEW PRIMARY)
    # Pattern: line starts with "#", followed by path containing "test", ends with .py
    header_pattern = (
        r"^#\s*((?:tests/|test/)?[a-zA-Z0-9_/.-]*test[a-zA-Z0-9_/.-]*\.py)\s*$"
    )
    header_matches = list(re.finditer(header_pattern, test_patch, re.MULTILINE))

    if header_matches:
        logger.debug(f"Found {len(header_matches)} test file headers in test_patch")

        for i, match in enumerate(header_matches):
            file_path = match.group(1).strip()
            start_pos = match.end()

            # Content is from end of this header to start of next header (or end)
            if i < len(header_matches) - 1:
                end_pos = header_matches[i + 1].start()
                content = test_patch[start_pos:end_pos].strip()
            else:
                content = test_patch[start_pos:].strip()

            if not content:
                continue

            # Preserve directory structure
            rel_path = Path(safe_filename(file_path))
            target = tests_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            test_file = target
            try:
                with open(test_file, "w", encoding="utf-8") as f:
                    f.write(content + "\n")
                logger.info(f"Wrote test file: {test_file} ({len(content)} bytes)")
            except OSError as e:
                logger.warning(f"Could not write test file {safe_name}: {e}")

        return

    # Format 2: "# Test file: path" - Split by markers (LEGACY)
    if "# Test file:" in test_patch or "#Test file:" in test_patch:
        parts = re.split(r"#\s*Test file:\s*", test_patch)
        for part in parts:
            if not part.strip():
                continue
            lines = part.split("\n", 1)
            filename = lines[0].strip()
            content = lines[1] if len(lines) > 1 else ""

            if not filename or not content.strip():
                continue

            # Preserve directory structure
            rel_path = Path(safe_filename(filename))
            target = tests_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            test_file = target
            try:
                with open(test_file, "w", encoding="utf-8") as f:
                    f.write(content.strip() + "\n")
                logger.debug(f"Extracted test file: {test_file}")
            except OSError as e:
                logger.warning(f"Could not write test file {safe_name}: {e}")
        return

    # Format 3: Git diff format
    if "diff --git" in test_patch:
        diffs = test_patch.split("diff --git")
        for diff in diffs[1:]:
            plus_match = re.search(r"\+\+\+ b/(.+?)(?:\n|$)", diff)
            if not plus_match:
                continue
            file_path = plus_match.group(1).strip()

            content_lines = []
            in_hunk = False

            for line in diff.split("\n"):
                if line.startswith("---") or line.startswith("+++"):
                    continue
                if line.startswith("index") or line.startswith("new file"):
                    continue
                if line.startswith("@@"):
                    in_hunk = True
                    continue
                if not in_hunk:
                    continue
                if line.startswith("+"):
                    content_lines.append(line[1:])

            if content_lines:
                while content_lines and not content_lines[-1].strip():
                    content_lines.pop()

                # Preserve directory structure
                rel_path = Path(safe_filename(file_path))
                target = tests_dir / rel_path
                target.parent.mkdir(parents=True, exist_ok=True)
                test_file = target
                try:
                    with open(test_file, "w", encoding="utf-8") as f:
                        f.write("\n".join(content_lines))
                        if content_lines:
                            f.write("\n")
                except OSError as e:
                    logger.warning(f"Could not write test file {safe_name}: {e}")
        return

    # Fallback: Write entire test_patch as test_swe_generated.py
    if test_patch.strip():
        test_file = tests_dir / "test_swe_generated.py"
        with open(test_file, "w", encoding="utf-8") as f:
            f.write(test_patch)
        logger.warning(f"Used fallback test_swe_generated.py for test_patch")


def update_workspace_with_prebuilt_image(
    workspace_path: Path | str,
    image_name: str,
) -> None:
    """Update workspace.yaml to mark Docker image as pre-built.

    Args:
        workspace_path: Path to workspace.yaml file
        image_name: Name of the pre-built Docker image
    """
    workspace_path = Path(workspace_path)
    if not workspace_path.exists():
        return

    with open(workspace_path, "r") as f:
        data = yaml.safe_load(f)

    # Update docker section
    data["docker"] = {
        "image": image_name,
        "build": False,
        "prebuilt": True,
    }

    # Update environment image
    data["environment"]["image"] = image_name

    with open(workspace_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
